channels:
  sources:
  - ramonaoptics
  - conda-forge
  - defaults
  targets:
  - [ramonaoptics, main]

github:
  user_or_org: ramonaoptics
travis:
  secure:
    BINSTAR_TOKEN: gbWgVvzCCl9yr01T2nZ4bTaN0m1lssEtlVmpKp8U9hmraGXUREtCrEpooKKxqtA6rTYy7hdH47WsSaMJuTLNSCMrnIqr527RolvYpzicsbTAVGZnpoLsaWaigcPt+jaheP9N9GmJ6OZ6J9AkLhFSD79pFvDL9jacU/3Vaomj1JmEnk0gOaO4fqb3fiqTtUjr/YpiT6dj5e9UD9Lou7+9/T0XroX5GvrgB2m9co76MiTij28JOQsbqCbr2Mj15y88CDqYpLcEgA+sFWGZJZVNKGTGswJVuwV5/juFcKYz3bp72D24xFXdsPkxtmSuqu9KrIdNKey0LaQdhAW4w2dLowXNAZGrCcCU06pfjw98g/8kYg6G7mqOj/uttPc1LVkuA51pcC5J47PtouneMXRfArPu7YUSEpmy7V53p13I5vJJPTL/t1oWN2FvRM9f8KRfcLBQTIcTJvvsDtIhtNvxcA850J0ABfgzsSL9GMQk+2Bc17N+WbA01bMRHwBC0Q19acObg1+36fb6hWVV8DbH6zHCffcUsQo32ZnPd9hOhZShpN2+hDYYZ54MVIOtgU2khlYuQxpw67p26vYfYr+lPu0JpzCcWSLlAoP0G1xg/yemAqJQ33KkCfdeg76dgoDWBIC6ugYp/J0pVPZ1jSXReJNnsRw9TC3kCHd4V7XWA4U=
appveyor:
  secure:
    BINSTAR_TOKEN: a8JN3c8s+67YV0kXG3aTQroHnYbyyZ9QNDK2cc/xJTFHzBnpTnu1jdOdFTb/Epek
