channels:
  sources:
  - ramonaoptics
  - conda-forge
  - defaults
  targets:
  - [ramonaoptics, main]

github:
  user_or_org: ramonaoptics
travis:
  secure:
    BINSTAR_TOKEN: MQCAJhP9gwoCpHNWYERtmcfdjkW4ruhDe2cn1mnFctbw6Z00+GjFCyKQk2jhYhKXVTSERhe2AHuryPHxvmzX5ylq3NYkgRYn3seoD62gFspRDGcKbnf2PfJUNIZii7KxQbxEn2DX3BWHSrLxrrLJJgND9fWJBS+N0trDoz06edhsO/AK4zm7H+tPBcpe4u/4xR/qLQE1dtX2SaXq+4UK0E8g14jiO4QwcHAROnEpbijfu1fa2xvy2qU+TwYPQATWHSVAFtm42rb0N+7XbMBvw0ip2xMk7Wq6+I4XGeK5HamBd2tQGy6WQab10ynBxdDZt5AEo/9pcPbID9LvLX8yST2pYuACWJvw1AD5n1DP6ACxsl5G4mbd0oyW6XXMN2SY5Ip3ZdMRsVbRQfslw9SZ2PnLXpONs+zKZ8/JzERxTrLckX0wv7006E76bl41iHxchV6eRyFGsgtZ5ZOUqzWUQ20bwWT96PZdgIMvhVJfFb8hDU2NjG7Mw1OQ94AFyGzFv0NP+USjOckqpeGAqD4haZcoucqzgagsh0X6tEPcxStQ9wrFMePaOupg1yt268nhADTj45zuuLYd2lj3msplC/SB+UUxRd6UKJ0GEVdai2zcwGi5/z/VtvBkaItAX5FpjR1nKDRmjGwT2beSO0IZVUId5tT5hI45UdeMu8Zbq54=
