channels:
  sources:
  - ramonaoptics
  - conda-forge
  - defaults
  targets:
  - [ramonaoptics, main]

github:
  user_or_org: ramonaoptics
travis:
  secure:
    BINSTAR_TOKEN: C/bLlxjMiWkb5Ksu4sXJwTCV99wGAc27eKOKVzHYlXD8fBnHi9GBA7OO/ZLrqhSUqsZjzBSy3eMX4+kV7IiX3DxypvXP9au5xNpQxMpHpb0SvUa2b4nDtnsom6U6NtbBErYBIiUqNgDDarSMv2B3RSCo/Nwh1TMpP70gnZgd/5oHcL1St535v+Oy218ZqKPsgVi2/9Mna9NXIvx8E1rx+zpCKq570odKZu+RxjeRr3/SqAr8U4XioPrZsuX8LDTS5fRCxwwrE1G/Y8qvNp4c7qwiPOIBmTtjL4QpcPI8SC/TCLbx7lK6hpa6V088pSesiINS7ub8RFzcW9BByTkHhAFLmj3ZtXzij+9jotzrCnYizRU2d6scAst0Tg6+6tbiVPzwgU0qjl7FbGYdMKqSWjYrI6BwvQvvT09ywTgTBJzBlFHMDbNlhuBr5kCczcus7bwAi6Gdi5CCm7pwQlWa/KkRhZKUgKKXV+g9SyGeXdzcQIRxIvI3gLr9/kIlAgBRAbMsfxjRK7YPX1d9m4ymOdDs2NBglcauu+v5agKtxiOQxx1RECDDqvHswocAjDCnO5mDqY7Q21qsOX/CL8PMt+dkUPzR6cPcGqKRKJ/ODQ7mwDzZM9QiCksr3hZx3tjA2oX9INHpcvkdpT019ZHY7rOuBjadSd5I1e1mkT1uvyo=
